### ISSUE TITLE
不知道应该如何使用

### ISSUE THREAD

**Issue by ayaseruri** [wuyouzhuguli/Material-Design#1]
hi，我是一个安卓开发者，很喜欢这个主题，可是不知道应该如何使用。
我尝试按照：https://hexo.io/zh-cn/docs/themes.html 中描述的方式使用，但是报错。请问能否补充一下 readme？万分感谢你的创作。

**Comment by wuyouzhuguli** [comment]
抱歉，这是蚂蚁笔记（Leanote）博客的主题，不是hexo主题额，sorry😅

**Comment by ayaseruri** [comment]
那太感谢啦
